name: Build App on new release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    name: Build, sign and release app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Build and sign app
        run: ./gradlew assembleRelease --no-daemon
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_STORE_PATH: "release.jks"

      # Uploads to the action results if not pointed at a tag
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          name: "psychonautwiki-journal_${{ github.ref_name }}.apk"
          path: "app/build/outputs/apk/release/app-release.apk"
          if-no-files-found: error

      # Creates a release if pointed at a tag
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "app/build/outputs/apk/release/app-release.apk"
          fail_on_unmatched_files: true
          make_latest: true
